name: open_match
description: gRPC generated client for Open Match - a library for hosting, running and scaling
  dedicated game servers on Kubernetes.
version: 1.6.0
homepage: https://markvideon.dev

environment:
  sdk: '>=2.18.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  fixnum: ^1.0.1
  grpc: ^3.1.0
  protobuf: ^2.1.0
